server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: swagger-ui.html
    operationsSorter: method